name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: totemo
authors: [totemo]
main: nu.nerd.alert.NerdAlert

permissions:
  nerdalert.admin:
    description: Permission to administer the plugin.
    default: op

commands:
  nerdalert:
    description: Reload the configuration.
    permission: nerdalert.admin
    usage: |
      /<command> reload - Reload the configuration.
      /<command> event <key> [<num> <units>] - Display a countdown to restart
        or shutdown using broadcasts and/or titles.
